server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/moban?useUnicode=true&characterEncoding=utf8&returnAffectedCount=true
    hikari:
      # 连接池最大连接数，默认是 10
      maximum-pool-size: 60
      # 链接超时时间，默认 30000(30 秒)
      connection-timeout: 60000
      # 空闲连接存活最大时间，默认 600000(10 分钟)
      idle-timeout: 60000
      # 连接将被测试活动的最大时间量
      validation-timeout: 3000
      # 此属性控制池中连接的最长生命周期，值 0 表示无限生命周期，默认 1800000(30 分钟)
      max-lifetime: 60000
      # 连接到数据库时等待的最长时间(秒)
      login-timeout: 5
      # 池中维护的最小空闲连接数
      minimum-idle: 10
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
#  mvc:
#    static-path-pattern: /web-static/**
#  web:
#    resources:
#      static-locations: file:imgs

mybatis-plus:
  configuration:
    use-generated-keys: true
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
swagger:
  enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    #operations-sorter: order
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      display-name: '测试'
      paths-to-match: '/**'
      packages-to-scan: org.springbus.moban
  default-flat-param-object: true

knife4j:
  enable: true
  setting:
    language: zh_cn
#    swagger-model-name: 实体类列表
#  documents:
#    - name: 标题1
#      locations: classpath:markdown/*
#      group: 测试
#    - name: 标题2
#      locations: classpath:markdown1/*
#      group: 用户模块
#  basic:
#    enable: false
#    username: abc
#    password: 123
#  insight:
#    enable: true
#    service-name: boot3
#    secret: S6CsnS8AnPVyb8vvChcdXm4R3p6A6KlAISxBg3IIEgk=
#    server: http://localhost:10086
#    namespace: spring3